import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState } from "react";
import InputEns from '../components/inputEns';
import LoginCard from '../components/communitySpace/LoginCard';
import Container from '../components/Container';
import LeaderBoard from '../components/LeaderBoard';
import Footer from '../components/footer';

export default function Home({ ...props }) {

  return (
    <>
      <Head>
        <title>ORG3 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container} style={{
        overflow: "hidden",
        backgroundImage: "url(/background.png)",
        backgroundSize: "cover",
        backgroundColor: "#4E86F7",
        width: "100vw",
        height: "850px",
        minHeight: "100vh",
        // display: "flex",
        // flexDirection: "column",
        // justifyContent: "space-between"
      }
      }>
        <Container marginTop={true}>
          <div
            className='landing-page'
            style={{
              display: "flex", justifyContent: "space-around", alignContent: "top", marginTop: 160
            }}>
            <LoginCard></LoginCard>
            <LeaderBoard />
          </div>
        </Container>
        <Footer light />
      </div>
    </>
  )
}
